development:
    lang: "pt"
    base: ""
    db: "teste"
    couchdb: "http://couchdb:5984"
    elasticsearch: "http://elasticsearch:9200"
    floradata: "http://floradata"
test:
    lang: "pt"
    base: ""
    db: "cncflora_test"
    couchdb: "http://couchdb:5984"
    elasticsearch: "http://elasticsearch:9200"
    floradata: "http://floradata"
production:
    lang: "pt"
    base: "/services"
    db: "public"
    couchdb: "http://couchdb:5984"
    elasticsearch: "http://elasticsearch:9200"
    floradata: "http://floradata"
