development:
    lang: "pt"
    base: ""
    db: "cncflora"
    couchdb: "http://192.168.50.15:5984"
    elasticsearch: "http://192.168.50.15:9200"
test:
    lang: "pt"
    base: ""
    db: "cncflora_test"
    couchdb: "http://192.168.50.15:5984"
    elasticsearch: "http://192.168.50.15:9200"
production:
    lang: "pt"
    base: "/services"
    db: "public"
    couchdb: "http://$HOST/couchdb"
    elasticsearch: "http://$HOST/elasticsearch"
